### ISSUE TITLE
Epic Loot "Weightless" enchantment breaks backpacks

### ISSUE THREAD

**Issue by raziell74** [Emrik-North/JotunnBackpacks#21]
At least i'm pretty confident it is the weightless enchant that's breaking it. The logs are showing this error repeating in reference to JotunnBackpacks.Patches+GetWeight_Patch.Postfix.

Here's the error that's repeating in the logs

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
JotunnBackpacks.Patches+GetWeight_Patch.Postfix (ItemDrop+ItemData __instance, System.Single& __result) (at <a9699d37a58941efaea41f420c9d0319>:0)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetWeight>(ItemDrop/ItemData)
EpicLoot.MagicItemTooltip_ItemDrop_Patch.Prefix (System.String& __result, ItemDrop+ItemData item, System.Int32 qualityLevel, System.Boolean crafting) (at <12595b05c14542b187994bedef0ab72e>:0)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetTooltip>(ItemDrop/ItemData,int,bool)
ItemDrop+ItemData.GetTooltip () (at <35c0f7aa1999477788815a7bf78200d7>:0)
EpicLoot.InventoryGrid_CreateItemTooltip_MagicItemComponent_Patch.Prefix (ItemDrop+ItemData item, UITooltip tooltip) (at <12595b05c14542b187994bedef0ab72e>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::CreateItemTooltip>(InventoryGrid,ItemDrop/ItemData,UITooltip)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <35c0f7aa1999477788815a7bf78200d7>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateContainer>(InventoryGui,Player)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)`

**Comment by Vapok** [comment]
Get 2.1.1 off the stores. I just fixed this issue.
