### ISSUE TITLE
NRE on load 

### ISSUE THREAD

**Issue by sbtoonz** [Emrik-North/JotunnBackpacks#4]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
JotunnBackpacks.Patches+GetWeight_Patch.Postfix (ItemDrop+ItemData __instance, System.Single& __result) (at <17d04ace0a90448a96ced74bbdd221b5>:0)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetWeight>(ItemDrop/ItemData)
(wrapper dynamic-method) Inventory.DMD<Inventory::UpdateTotalWeight>(Inventory)
(wrapper dynamic-method) Inventory.DMD<Inventory::Changed>(Inventory)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,ItemDrop/ItemData,int,int,int)
ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix (Inventory __instance, System.Boolean& __result, System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName) (at <45153377f0be4fc697d4f28115fd20b2>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,string,int,single,Vector2i,bool,int,int,long,string)
(wrapper dynamic-method) Inventory.DMD<Inventory::Load>(Inventory,ZPackage)
Player.Load (ZPackage pkg) (at <1b865f8b3455488592cdc401081112e3>:0)
PlayerProfile.LoadPlayerData (Player player) (at <1b865f8b3455488592cdc401081112e3>:0)
FejdStartup.SetupCharacterPreview (PlayerProfile profile) (at <1b865f8b3455488592cdc401081112e3>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::UpdateCharacterList>(FejdStartup)
FejdStartup.SetSelectedProfile (System.String filename) (at <1b865f8b3455488592cdc401081112e3>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

**Comment by Emrik-North** [comment]
Thanks! I'm not sure what this could come from. I haven't seen it before. Were you able to reproduce it? Sorry for the late reply.

**Comment by Geethebluesky** [comment]
I think I got a similar bug, if not the same?

This was triggered after a teleport (I was moving things from one base to another), and then repeated endlessly. Eventually I couldn't open any chests, or get into the backpack's inventory.


[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
JotunnBackpacks.Patches+GetWeight_Patch.Postfix (ItemDrop+ItemData __instance, System.Single& __result) (at <549627978d094e1ab18a3cf1a7b69fa5>:0)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetWeight>(ItemDrop/ItemData)
(wrapper dynamic-method) Inventory.DMD<Inventory::UpdateTotalWeight>(Inventory)
(wrapper dynamic-method) Inventory.DMD<Inventory::Changed>(Inventory)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,ItemDrop/ItemData,int,int,int)
ExtendedItemDataFramework.Inventory_AddItemFromLoad_Patch.Prefix (Inventory __instance, System.Boolean& __result, System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName) (at <67fcacf4676c4bb083c4a471673662ad>:0)
(wrapper dynamic-method) Inventory.DMD<Inventory::AddItem>(Inventory,string,int,single,Vector2i,bool,int,int,long,string)
(wrapper dynamic-method) Inventory.DMD<Inventory::Load>(Inventory,ZPackage)
(wrapper dynamic-method) Container.DMD<Container::Load>(Container)
Container.CheckForChanges () (at <ac3ebdd00e8c4012a671c8993fd5e3e0>:0)

**Comment by Geethebluesky** [comment]
... And it apparently corrupts something in the save, because it triggers immediately upon load and every container appears to be messed up, including regular chests.
