### ISSUE TITLE
Arctic Backpack dupe and character reset 

### ISSUE THREAD

**Issue by PenitentFleece** [Emrik-North/JotunnBackpacks#8]
Recently discovered that if an arctic backpack is removed from the inventory while equipped [either dropped or put in a chest] it will duplicate and seemingly corrupt the inventory its in?

Upon logging out the character is reset, total skill loss, no visible armor, but the inventory seems to stay in tact.

**Comment by BrandonT80** [comment]
Can confirm this still exists. Its so bad we are doing away with this mod unless its fixed, almost every single player has been corrupted because of this.
