### ISSUE TITLE
Poor network quality with backpacks equipped

### ISSUE THREAD

**Issue by SapphSky** [Emrik-North/JotunnBackpacks#9]
Hi there.
I'm writing this issue because my friends and I have confirmed that there is immense lag with the backpacks when equipped.

Condition: One or more players with a backpack equipped are within range of each other. 
Effects: Players joining the session with players w/ backpacks nearby have world streaming data bottle necked. Interactions with storage, doors, buildings, enemies, etc. are also buffered. Sent/Received data is increased between players.
Probability: Backpack data is being sent consistently between players.

**Comment by BrandonT80** [comment]
I confirm as well.

**Comment by HeberPcL** [comment]
Guys, if you are using EpicLoot. Please update the version and try again.
